### PR TITLE
Add GHC 9 support

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Fixes https://github.com/google/proto-lens/issues/415

### CODE REVIEW

**Comment by brandon-leapyear** [comment]
I'm getting an error building `proto-lens-tests` locally, not sure if I need to install something:
```
.../proto-lens/proto-lens-tests/test_proto3_optional.proto:7:12: Explicit 'optional' labels are disallowed in the Proto3 syntax. To define 'optional' fields in Proto3, simply remove the 'optional' label, as fields are 'optional' by default.
```
```bash
$ protoc --version
libprotoc 3.11.2
```

**Review by blackgnezdo — APPROVED** [review]

**Comment by blackgnezdo** [comment]
Sadly due to #405 we don't run Travis for real. I can merge this PR, but we won't have a good assurance this works.

**Comment by brandon-leapyear** [comment]
FWIW this works when building my company's code on GHC 9

**Comment by brandon-leapyear** [comment]
Any update on when this can be released to Hackage?

**Pull request merged**
