### PR TITLE
also expose timestamp

### PR DESCRIPTION
**Pull request by plredmond**
This change is [Reviewable](https://reviewable.io/reviews/google/proto-lens/175)

### CODE REVIEW

**Comment by judah** [comment]
Thanks for the patch!  The current HEAD uses hpack to generate the .cabal files; can you move your change to the `package.yaml` file instead?

Also, please add a note about this line in `proto-lens-protobuf-types/Changelog.md`.

**Comment by plredmond** [comment]
Sure, I'll do that.

**Comment by judah** [comment]
Also: please sign the CLA as described in the above message from googlebot.

**Comment by plredmond** [comment]
Looks like this got rolled into [0.3.0.0](https://hackage.haskell.org/package/proto-lens-protobuf-types) by somebody else. Thank you!

**Pull request closed without merging**
