### PR TITLE
Switch from test-framework to tasty.

### PR DESCRIPTION
**Pull request by judah**
test-framework isn't in Stackage nightly, in part due to
its dependency regex-posix not yet building with ghc-8.8.
test-framework also doesn't seem to be as actively developed
anymore.

Luckily, the translation was fairly mechanical.

### CODE REVIEW

**Comment by blackgnezdo** [comment]
Not sure if this is pre-existing, but worth fixing either way:
https://travis-ci.org/google/proto-lens/jobs/591141818
```
Preprocessing library for proto-lens-tests-0.1.0.1..
Building library for proto-lens-tests-0.1.0.1..
[1 of 3] Compiling Data.ProtoLens.TestUtil ( src/Data/ProtoLens/TestUtil.hs, dist/build/Data/ProtoLens/TestUtil.o )
[2 of 3] Compiling Paths_proto_lens_tests ( dist/build/autogen/Paths_proto_lens_tests.hs, dist/build/Paths_proto_lens_tests.o )
[3 of 3] Compiling Proto.Lib        ( dist/build/autogen/Proto/Lib.hs, dist/build/Proto/Lib.o )
Preprocessing test suite 'canonical_test' for proto-lens-tests-0.1.0.1..
GHCi, version 8.6.5: http://www.haskell.org/ghc/  :? for help
[1 of 3] Compiling Proto.Canonical  ( dist/build/canonical_test/autogen/Proto/Canonical.hs, interpreted )
[2 of 3] Compiling Proto.Canonical_Fields ( dist/build/canonical_test/autogen/Proto/Canonical_Fields.hs, interpreted )
[3 of 3] Compiling Main             ( tests/canonical_test.hs, interpreted )
Ok, three modules loaded.
*Proto.Canonical> 
<interactive>:1:1: error:
    • Variable not in scope: main
    • Perhaps you meant ‘Prelude.min’ (imported from Data.ProtoLens.Runtime.Prelude)
*Proto.Canonical> Leaving GHCi.
The command "case "$BUILD" in stack) STACK_ARGS=(--haddock --no-haddock-deps); $STACK build --bench --no-run-benchmarks "${STACK_ARGS[@]}" && $STACK test "${STACK_ARGS[@]}" && (cd proto-lens-tutorial && $STACK build "${STACK_ARGS[@]}");; cabal) ./travis-cabal.sh;; esac" exited with 0.
cache.2
store build cache
```

**Comment by blackgnezdo** [comment]
The main challenge with refactoring test is to make sure they continue to fail when they detect breakage. Could you try introduce some failures and see if they get caught?

**Comment by judah** [comment]
Sure, I tried a couple different ways to test this:

- Confirmed that I could still trigger this timeout with an infinite loop:
https://github.com/google/proto-lens/blob/c480b8e5f029563a32c11f0b60621333d9518ae1/proto-lens-tests/tests/enum_test.hs#L133

Added a bug in Data.ProtoLens.Encoding.getFiixed64 ignoring the top 8 bits, and confirmed that the tests failed correctly.

**Comment by judah** [comment]
I've seen the issue with `main` being undefined before; I'll look into fixing it.

**Pull request merged**
