### PR TITLE
Update installing-protoc.md : Added Proper ZIP file name

### PR DESCRIPTION
**Pull request by lahiri-phdworks**

### CODE REVIEW

**Comment by lahiri-phdworks** [comment]
> @googlebot I signed it!

@googlebot I signed it!

**Review by blackgnezdo — APPROVED** [review]

**Comment by blackgnezdo** [comment]
Thanks for the fix!

**Comment by blackgnezdo** [comment]
@judah, I don't see a way to merge this nor a link to the launched build. Did Travis even get triggered?

**Comment by lahiri-phdworks** [comment]
Yeah, a Travis build was triggered. 
https://travis-ci.com/github/lahiri-phdworks/proto-lens/builds/204571293
Strange that it isn't reflecting here. Do I miss out on something?

**Review by blackgnezdo — APPROVED** [review]

**Pull request merged**
