### PR TITLE
Changes to work with lts-15.2

### PR DESCRIPTION
**Pull request by dspies-leapyear**
Okay, this time fix the underlying issue instead of suppressing the warning

### CODE REVIEW

**Comment by judah** [comment]
Thanks for the improvement!

It looks like these changes break ghc-8.2; for example, `<>` wasn't exported from `Prelude` until `8.4.1`.

@blackgnezdo , any objection to just dropping 8.2 from our CI build and bumping our `base` lower bounds to `>= 4.11`?  8.2 was released two years ago (March 2018).

**Comment by blackgnezdo** [comment]
@judah, not at all. 8.2 is more than 2 releases behind.

**Comment by judah** [comment]
Sounds good. @dspies-leapyear, could you please increase lower bounds to `base >= 4.11` and remove these entries for 8.2.2 from CI?

https://github.com/google/proto-lens/blob/7bb31dc868161a756b2744676425ac8f7e5860fa/.travis.yml#L17

https://github.com/google/proto-lens/blob/7bb31dc868161a756b2744676425ac8f7e5860fa/.travis.yml#L26

After that I can merge your change.

**Comment by dspies-leapyear** [comment]
Done

**Comment by judah** [comment]
@blackgnezdo, looks like I'm not allowed to merge PRs; any idea why? Want to merge it yourself?

**Comment by blackgnezdo** [comment]
See if it works now? The permission settings aren't entirely obvious.

**Pull request merged**
