### PR TITLE
Feature/prisms

### PR DESCRIPTION
**Pull request by FintanH**
This PR outlines the adding of prisms for `oneof` message fields.

A message:
```
message Foo
    oneof bar
        int32 anInt = 1;
        float aFloat = 2;
    }
}
```

Would generate the following functions:
```hs
_Foo'AnInt :: Prism' Foo'Bar Int32
_Foo'AFloat :: Prism' Foo'Bar Float
```

The use of this would be to focus in on the value as follows:
```hs
f :: Foo -> Just Float
f foo = foo ^? maybe'bar . _Just . _Foo'AFloat
```

---
This change is [Reviewable](https://reviewable.io/reviews/google/proto-lens/160)

### CODE REVIEW

**Comment by FintanH** [comment]
I signed it! 😁

**Comment by FintanH** [comment]
Fixed email issue using interactive rebase (hopefully)

**Comment by judah** [comment]
Overall looks good; mostly code organization nits.

---

Review status: 0 of 8 files reviewed at latest revision, 8 unresolved discussions.

---

*[lens-labels/package.yaml, line 21 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBXaojm5VRr7KX7jL:-L-rBXaojm5VRr7KX7jM:bi161u2) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/package.yaml#L21)):*
> ```YAML
>     - Lens.Labels
>     - Lens.Labels.Unwrapped
>     - Lens.Prism
> ```

Let's rename this module `Lens.Labels.Prism` to avoid clashing with other packages.

---

*[lens-labels/src/Lens/Prism.hs, line 3 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBlNj2HW2Xw3Rrbb9:-L-rBlNj2HW2Xw3RrbbA:b-aff38g) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L3)):*
> ```Haskell
> {-# LANGUAGE RankNTypes #-}
> 
> module Lens.Prism where
> ```

Use an explicit export list, and add a module-level Haddock comment.

---

*[lens-labels/src/Lens/Prism.hs, line 11 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rIDo-YEffq-0ccbLe:-L-rIDo-YEffq-0ccbLf:blazrts) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L11)):*
> ```Haskell
> -- Prism Internals
> ------------------------------------------------------------------------------
> type Prism s t a b = forall p f. (Choice p, Applicative f) => p a (f b) -> p s (f t)
> ```

Looking at this code, I wonder whether it would be more consistent for `lens-labels` to define these types in terms of the newtyped `LensFn`:  https://github.com/google/proto-lens/blob/master/lens-labels/src/Lens/Labels.hs#L68 ?

Maybe it's not worth it, since we're not generating overloaded names for the prisms.

Up to you.

---

*[proto-lens/package.yaml, line 7 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBs4BijKBompxvbQ7:-L-rBs4BijKBompxvbQ8:blffzju) ([raw file](https://github.com/google/proto-lens/blob/b342f24e6366474434a48f9510ea42f1bc46d64f/proto-lens/package.yaml#L7)):*
> ```YAML
>   The proto-lens library provides to protocol buffers using modern
>   Haskell language and library patterns.  Specifically, it provides:
>    
> ```

Revert this change; it breaks the Haddock formatting due to `hpack`/`stack`/`Cabal` being annoying.

---

*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, line 240 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rC1qMo5yvJcDsBaPC:-L-rC1qMo5yvJcDsBaPD:bns5usg) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs#L240)):*
> ```Haskell
> type Pat = Syntax.Pat ()
> 
> identCons :: String -> Name
> ```

You can just use `fromString` for this.  (See the `IsString Name` instance below.)

---

*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, line 323 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rJVDOD_C_jjOKTiFt:-L-rJVDOD_C_jjOKTiFu:b-6ctq7x) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs#L323)):*
> ```Haskell
> --        }
> -- haskell: _Foo'C :: Prism' Bar'C Float
> --          _Foo'S :: Prism' Bar'S Sub
> ```

Add a comment of what the generated implementation looks like for, say, _Foo'C.

---

*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, line 361 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rD6AigwbMN6H8vnGk:-L-rD6AigwbMN6H8vnGl:bpeq8lr) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs#L361)):*
> ```Haskell
>         generatePrism otherwiseCase oneofCase =
>             let consName = caseConstructorName oneofCase
>                 funName = modifyName ("_" ++) $ consName
> ```

Code organization nit:  in Definitions.hs, add a new record field `casePrismName` which has the '_': https://github.com/google/proto-lens/blob/master/proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs#L144
And then just use it here instead of defining/calling `modifyName`

That separation lets us distinguish decisions about names from the rest of code generation.

---

*[proto-lens-tests/tests/oneof_test.hs, line 22 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rCdpWPJyoWWxFYlHb:-L-rCdpWPJyoWWxFYlHc:b-eur5ls) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-tests/tests/oneof_test.hs#L22)):*
> ```Haskell
> defFoo = def
> 
> -- So we do not pull in the lens library we are putting some
> ```

Would it make sense to move these to `Lens.Labels.Prism`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160#-:-L-rJuFhJdrGHscWZzVl:bj5dtxs)*

**Comment by FintanH** [comment]
*[lens-labels/package.yaml, line 21 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBXaojm5VRr7KX7jL:-L-vjPUeb7vuZjG7-phq:b-r5pnhv) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/package.yaml#L21)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Let's rename this module `Lens.Labels.Prism` to avoid clashing with other packages.
</blockquote></details>

Done. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[lens-labels/src/Lens/Prism.hs, line 11 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rIDo-YEffq-0ccbLe:-L-vk1D7PY-LsYPhtxb7:bvkktdw) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L11)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Looking at this code, I wonder whether it would be more consistent for `lens-labels` to define these types in terms of the newtyped `LensFn`:  https://github.com/google/proto-lens/blob/master/lens-labels/src/Lens/Labels.hs#L68 ?

Maybe it's not worth it, since we're not generating overloaded names for the prisms.

Up to you.
</blockquote></details>

I didn't go for this since, as you mentioned, we're not overloading and if it comes to needing it then it can be in a different PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, line 240 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rC1qMo5yvJcDsBaPC:-L-vkDiBw-Jt6vAn1d0M:bg85416) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs#L240)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

You can just use `fromString` for this.  (See the `IsString Name` instance below.)
</blockquote></details>

This ended up being for something I was attempting to do and it wasn't being used anyway so removed it :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, line 243 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-vkUaLSIvzdt-paM-x:-L-vkUaLSIvzdt-paM-y:bdzldyj) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs#L243)):*
> ```Haskell
> identCons = Syntax.Ident ()
> 
> modifyName :: (String -> String) -> Name -> Name
> ```

Should I remove this with the change with new addition `casePrismName` or should I leave it for future use?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, line 323 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rJVDOD_C_jjOKTiFt:-L-vkh10PGdMfyQ_WXIs:b-r5pnhv) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs#L323)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Add a comment of what the generated implementation looks like for, say, _Foo'C.
</blockquote></details>

Done. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs, line 361 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rD6AigwbMN6H8vnGk:-L-vkkU3qAeGKHB8ms3t:b-r5pnhv) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Generate.hs#L361)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Code organization nit:  in Definitions.hs, add a new record field `casePrismName` which has the '_': https://github.com/google/proto-lens/blob/master/proto-lens-protoc/src/Data/ProtoLens/Compiler/Definitions.hs#L144
And then just use it here instead of defining/calling `modifyName`

That separation lets us distinguish decisions about names from the rest of code generation.
</blockquote></details>

Done. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[proto-lens-tests/tests/oneof_test.hs, line 22 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rCdpWPJyoWWxFYlHb:-L-vkocCdOBiWqJAPH2_:bq537ye) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-tests/tests/oneof_test.hs#L22)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Would it make sense to move these to `Lens.Labels.Prism`?
</blockquote></details>

I think it makes sense ya :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[lens-labels/src/Lens/Prism.hs, line 3 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBlNj2HW2Xw3Rrbb9:-L-vjYlNfPc5DMvq9yDE:b-r5pnhv) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L3)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

Use an explicit export list, and add a module-level Haddock comment.
</blockquote></details>

Done. :+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by judah** [comment]
Review status: 0 of 9 files reviewed at latest revision, 2 unresolved discussions.

---

*[lens-labels/src/Lens/Prism.hs, line 3 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBlNj2HW2Xw3Rrbb9:-L064hsVjFEwkfyCblVj:b-1vb0wo) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L3)):*
<details><summary><i>Previously, FintanH (Fintan Halpenny) wrote…</i></summary><blockquote>

Done. :+1: 
</blockquote></details>

I don't see this change in the latest revision? ("r4" in reviewable)

---

*[proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs, line 243 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-vkUaLSIvzdt-paM-x:-L-z-3p7ROeSyAIY_Fya:b-5cqkta) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/proto-lens-protoc/src/Data/ProtoLens/Compiler/Combinators.hs#L243)):*
<details><summary><i>Previously, FintanH (Fintan Halpenny) wrote…</i></summary><blockquote>

Should I remove this with the change with new addition `casePrismName` or should I leave it for future use?
</blockquote></details>

Remove it; it intentionally doesn't exist to help the separation between the two modules.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by FintanH** [comment]
*[lens-labels/src/Lens/Prism.hs, line 3 at r2](https://reviewable.io:443/reviews/google/proto-lens/160#-L-rBlNj2HW2Xw3Rrbb9:-L06QjCXeQRxJbiN9OVt:b-ecte9m) ([raw file](https://github.com/google/proto-lens/blob/8a3ded83c72c60495d2a0c1077389c5f2135f298/lens-labels/src/Lens/Prism.hs#L3)):*
<details><summary><i>Previously, judah (Judah Jacobson) wrote…</i></summary><blockquote>

I don't see this change in the latest revision? ("r4" in reviewable)
</blockquote></details>

Somehow Lens.Prism was still hanging around. It's now Lens.Labels.Prism. I just removed the old one

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160)*

**Comment by judah** [comment]
:lgtm:

---

Review status: 0 of 7 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/google/proto-lens/160#-:-L06bfFBT1ZUbd06wzJP:bnfp4nl)*

**Pull request merged**
