### PR TITLE
Updating protoc version

### PR DESCRIPTION
**Pull request by AnupKumarPanwar**
Latest version released is v3.7.1

### CODE REVIEW

**Comment by judah** [comment]
Thank you for the patch!  Can you please also update our Travis CI script here?
https://github.com/google/proto-lens/blob/798a5c007814e3daab41cfa26e640ccdfa3ae6e3/.travis.yml#L41

That would help us verify that the instructions in the installation guide still work properly.

**Comment by AnupKumarPanwar** [comment]
Done. Updated the version to 3.7.1 in `.travis.yml`.

**Comment by AnupKumarPanwar** [comment]
@judah Please review

**Comment by judah** [comment]
I'm not sure why this is failing CI.  It seems unrelated to this patch though, so I'll force-submit it.

**Pull request merged**
